version: '3.8'

services:

  # Servicio para el microservicio business
  business:
    image: remodify-microservice-business
    container_name: business
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=autorack.proxy.rlwy.net
      - DB_PORT=41993
      - DB_USER=root
      - DB_PASSWORD=IvKfalhjWHIxGEcfvIFKHaVQpvXJJAaF
    networks:
      - app-network
    restart: unless-stopped

  # Servicio para el microservicio IAM
  iam:
    image: remodify-microservice-iam
    container_name: iam
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=autorack.proxy.rlwy.net
      - DB_PORT=41993
      - DB_USER=root
      - DB_PASSWORD=IvKfalhjWHIxGEcfvIFKHaVQpvXJJAaF
    networks:
      - app-network
    restart: unless-stopped

  # Servicio para el microservicio project
  project:
    image: remodify-microservice-project
    container_name: project
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=autorack.proxy.rlwy.net
      - DB_PORT=41993
      - DB_USER=root
      - DB_PASSWORD=IvKfalhjWHIxGEcfvIFKHaVQpvXJJAaF
    networks:
      - app-network
    restart: unless-stopped

  # Servicio para el microservicio reviews
  reviews:
    image: remodify-microservice-reviews
    container_name: reviews
    ports:
      - "8084:8084"
    environment:
      - DB_HOST=autorack.proxy.rlwy.net
      - DB_PORT=41993
      - DB_USER=root
      - DB_PASSWORD=IvKfalhjWHIxGEcfvIFKHaVQpvXJJAaF
    networks:
      - app-network
    restart: unless-stopped

  # Servicio para el microservicio projectrequest
  projectrequest:
    image: remodify-microservice-projectrequest
    container_name: projectrequest
    ports:
      - "8085:8085"
    environment:
      - DB_HOST=autorack.proxy.rlwy.net
      - DB_PORT=41993
      - DB_USER=root
      - DB_PASSWORD=IvKfalhjWHIxGEcfvIFKHaVQpvXJJAaF
    networks:
      - app-network
    restart: unless-stopped

# Definici√≥n de la red personalizada
networks:
  app-network:
    driver: bridge
